bin: validate default branch in initialize-git-repository

diff --git a/~/.local/bin/initialize-git-repository b/~/.local/bin/initialize-git-repository
--- a/~/.local/bin/initialize-git-repository
+++ b/~/.local/bin/initialize-git-repository
@@ -32,4 +32,9 @@ git remote set-head origin --auto
 trees="${name}"/trees
 branch="$(git name-rev --name-only origin/HEAD)"
 
+if [[ -z "${branch}" ]]; then
+  1>&2 echo 'Failed to determine default branch from origin/HEAD'
+  exit 3
+fi
+
 git worktree add "${trees}"/"${branch}" "${branch}"
